import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/src/app/styles/globals.scss';
import { ReactNode } from 'react';
import { Header } from '@/src/widgets/Header';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
