import { nanoid } from 'nanoid';

import { TProduct } from '@/entities/Product';

const data: TProduct[] = [
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-big-potatos.jpg',
    title: 'Big Potatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-chanise-cabbage.jpg',
    title: 'Chanise Cabbage',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
    tags: [
      {
        type: 'black',
        text: 'Out of Stock',
      },
    ],
  },
  {
    id: nanoid(),
    img: '/images/product-eggplant.jpg',
    title: 'Eggplant',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-cauliflower.jpg',
    title: 'Fresh Cauliflower',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-apple.jpg',
    title: 'Green Apple',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-chilli.jpg',
    title: 'Green Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-green-cucumber.jpg',
    title: 'Green Cucumber',
    price: { USD: 14.99, EUR: 12.2 },
    priceOld: { USD: 20.99, EUR: 18.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-letucce.jpg',
    title: 'Green Lettuce',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-green-ladies-finger.jpg',
    title: 'Ladies Finger',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-red-capsicum.jpg',
    title: 'Green Capsicum',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-red-chilli.jpg',
    title: 'Red Chili',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },

  {
    id: nanoid(),
    img: '/images/product-tomatos.jpg',
    title: 'Red Tomatos',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
  {
    id: nanoid(),
    img: '/images/product-mango.jpg',
    title: 'Surjapur Mango',
    price: { USD: 14.99, EUR: 12.2 },
    path: '#',
    rating: 4,
  },
];

export const getCatalogItems = () => {
  return { items: data };
};
